// Code generated by capnpc-go. DO NOT EDIT.

package bytestream

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type Service capnp.Client

// Service_TypeID is the unique identifier for the type Service.
const Service_TypeID = 0xcda9e973a872b6fc

func (c Service) Get(ctx context.Context, params func(Service_get_Params) error) (Service_get_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xcda9e973a872b6fc,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:Service",
			MethodName:    "get",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Service_get_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Service_get_Results_Future{Future: ans.Future()}, release

}

func (c Service) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Service) String() string {
	return "Service(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Service) AddRef() Service {
	return Service(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Service) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Service) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Service) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Service) DecodeFromPtr(p capnp.Ptr) Service {
	return Service(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Service) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Service) IsSame(other Service) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Service) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Service) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Service_Server is a Service with a local implementation.
type Service_Server interface {
	Get(context.Context, Service_get) error
}

// Service_NewServer creates a new Server from an implementation of Service_Server.
func Service_NewServer(s Service_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Service_Methods(nil, s), s, c)
}

// Service_ServerToClient creates a new Client from an implementation of Service_Server.
// The caller is responsible for calling Release on the returned Client.
func Service_ServerToClient(s Service_Server) Service {
	return Service(capnp.NewClient(Service_NewServer(s)))
}

// Service_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Service_Methods(methods []server.Method, s Service_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xcda9e973a872b6fc,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:Service",
			MethodName:    "get",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Get(ctx, Service_get{call})
		},
	})

	return methods
}

// Service_get holds the state for a server call to Service.get.
// See server.Call for documentation.
type Service_get struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Service_get) Args() Service_get_Params {
	return Service_get_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Service_get) AllocResults() (Service_get_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_get_Results(r), err
}

// Service_List is a list of Service.
type Service_List = capnp.CapList[Service]

// NewService_List creates a new list of Service.
func NewService_List(s *capnp.Segment, sz int32) (Service_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Service](l), err
}

type Service_get_Params capnp.Struct

// Service_get_Params_TypeID is the unique identifier for the type Service_get_Params.
const Service_get_Params_TypeID = 0xb4e4ff72540e8e7b

func NewService_get_Params(s *capnp.Segment) (Service_get_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_get_Params(st), err
}

func NewRootService_get_Params(s *capnp.Segment) (Service_get_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_get_Params(st), err
}

func ReadRootService_get_Params(msg *capnp.Message) (Service_get_Params, error) {
	root, err := msg.Root()
	return Service_get_Params(root.Struct()), err
}

func (s Service_get_Params) String() string {
	str, _ := text.Marshal(0xb4e4ff72540e8e7b, capnp.Struct(s))
	return str
}

func (s Service_get_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_get_Params) DecodeFromPtr(p capnp.Ptr) Service_get_Params {
	return Service_get_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_get_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_get_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_get_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_get_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Service_get_Params_List is a list of Service_get_Params.
type Service_get_Params_List = capnp.StructList[Service_get_Params]

// NewService_get_Params creates a new list of Service_get_Params.
func NewService_get_Params_List(s *capnp.Segment, sz int32) (Service_get_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Service_get_Params](l), err
}

// Service_get_Params_Future is a wrapper for a Service_get_Params promised by a client call.
type Service_get_Params_Future struct{ *capnp.Future }

func (f Service_get_Params_Future) Struct() (Service_get_Params, error) {
	p, err := f.Future.Ptr()
	return Service_get_Params(p.Struct()), err
}

type Service_get_Results capnp.Struct

// Service_get_Results_TypeID is the unique identifier for the type Service_get_Results.
const Service_get_Results_TypeID = 0xca1efa208c6f4595

func NewService_get_Results(s *capnp.Segment) (Service_get_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_get_Results(st), err
}

func NewRootService_get_Results(s *capnp.Segment) (Service_get_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_get_Results(st), err
}

func ReadRootService_get_Results(msg *capnp.Message) (Service_get_Results, error) {
	root, err := msg.Root()
	return Service_get_Results(root.Struct()), err
}

func (s Service_get_Results) String() string {
	str, _ := text.Marshal(0xca1efa208c6f4595, capnp.Struct(s))
	return str
}

func (s Service_get_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_get_Results) DecodeFromPtr(p capnp.Ptr) Service_get_Results {
	return Service_get_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_get_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_get_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_get_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_get_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Service_get_Results) Bsr() ByteStreamReturner {
	p, _ := capnp.Struct(s).Ptr(0)
	return ByteStreamReturner(p.Interface().Client())
}

func (s Service_get_Results) HasBsr() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Service_get_Results) SetBsr(v ByteStreamReturner) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// Service_get_Results_List is a list of Service_get_Results.
type Service_get_Results_List = capnp.StructList[Service_get_Results]

// NewService_get_Results creates a new list of Service_get_Results.
func NewService_get_Results_List(s *capnp.Segment, sz int32) (Service_get_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Service_get_Results](l), err
}

// Service_get_Results_Future is a wrapper for a Service_get_Results promised by a client call.
type Service_get_Results_Future struct{ *capnp.Future }

func (f Service_get_Results_Future) Struct() (Service_get_Results, error) {
	p, err := f.Future.Ptr()
	return Service_get_Results(p.Struct()), err
}
func (p Service_get_Results_Future) Bsr() ByteStreamReturner {
	return ByteStreamReturner(p.Future.Field(0, nil).Client())
}

type ByteStreamReturner capnp.Client

// ByteStreamReturner_TypeID is the unique identifier for the type ByteStreamReturner.
const ByteStreamReturner_TypeID = 0x88b0b5346f219aca

func (c ByteStreamReturner) GetConnector(ctx context.Context, params func(ByteStreamReturner_getConnector_Params) error) (ByteStreamReturner_getConnector_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x88b0b5346f219aca,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:ByteStreamReturner",
			MethodName:    "getConnector",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ByteStreamReturner_getConnector_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ByteStreamReturner_getConnector_Results_Future{Future: ans.Future()}, release

}

func (c ByteStreamReturner) Inflighter(ctx context.Context, params func(ByteStreamReturner_inflighter_Params) error) (ByteStreamReturner_inflighter_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x88b0b5346f219aca,
			MethodID:      1,
			InterfaceName: "byte-stream.capnp:ByteStreamReturner",
			MethodName:    "inflighter",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ByteStreamReturner_inflighter_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ByteStreamReturner_inflighter_Results_Future{Future: ans.Future()}, release

}

func (c ByteStreamReturner) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c ByteStreamReturner) String() string {
	return "ByteStreamReturner(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c ByteStreamReturner) AddRef() ByteStreamReturner {
	return ByteStreamReturner(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c ByteStreamReturner) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c ByteStreamReturner) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c ByteStreamReturner) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (ByteStreamReturner) DecodeFromPtr(p capnp.Ptr) ByteStreamReturner {
	return ByteStreamReturner(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c ByteStreamReturner) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c ByteStreamReturner) IsSame(other ByteStreamReturner) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c ByteStreamReturner) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c ByteStreamReturner) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A ByteStreamReturner_Server is a ByteStreamReturner with a local implementation.
type ByteStreamReturner_Server interface {
	GetConnector(context.Context, ByteStreamReturner_getConnector) error

	Inflighter(context.Context, ByteStreamReturner_inflighter) error
}

// ByteStreamReturner_NewServer creates a new Server from an implementation of ByteStreamReturner_Server.
func ByteStreamReturner_NewServer(s ByteStreamReturner_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ByteStreamReturner_Methods(nil, s), s, c)
}

// ByteStreamReturner_ServerToClient creates a new Client from an implementation of ByteStreamReturner_Server.
// The caller is responsible for calling Release on the returned Client.
func ByteStreamReturner_ServerToClient(s ByteStreamReturner_Server) ByteStreamReturner {
	return ByteStreamReturner(capnp.NewClient(ByteStreamReturner_NewServer(s)))
}

// ByteStreamReturner_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ByteStreamReturner_Methods(methods []server.Method, s ByteStreamReturner_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x88b0b5346f219aca,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:ByteStreamReturner",
			MethodName:    "getConnector",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetConnector(ctx, ByteStreamReturner_getConnector{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x88b0b5346f219aca,
			MethodID:      1,
			InterfaceName: "byte-stream.capnp:ByteStreamReturner",
			MethodName:    "inflighter",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Inflighter(ctx, ByteStreamReturner_inflighter{call})
		},
	})

	return methods
}

// ByteStreamReturner_getConnector holds the state for a server call to ByteStreamReturner.getConnector.
// See server.Call for documentation.
type ByteStreamReturner_getConnector struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ByteStreamReturner_getConnector) Args() ByteStreamReturner_getConnector_Params {
	return ByteStreamReturner_getConnector_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ByteStreamReturner_getConnector) AllocResults() (ByteStreamReturner_getConnector_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ByteStreamReturner_getConnector_Results(r), err
}

// ByteStreamReturner_inflighter holds the state for a server call to ByteStreamReturner.inflighter.
// See server.Call for documentation.
type ByteStreamReturner_inflighter struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ByteStreamReturner_inflighter) Args() ByteStreamReturner_inflighter_Params {
	return ByteStreamReturner_inflighter_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ByteStreamReturner_inflighter) AllocResults() (ByteStreamReturner_inflighter_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStreamReturner_inflighter_Results(r), err
}

// ByteStreamReturner_List is a list of ByteStreamReturner.
type ByteStreamReturner_List = capnp.CapList[ByteStreamReturner]

// NewByteStreamReturner_List creates a new list of ByteStreamReturner.
func NewByteStreamReturner_List(s *capnp.Segment, sz int32) (ByteStreamReturner_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[ByteStreamReturner](l), err
}

type ByteStreamReturner_getConnector_Params capnp.Struct

// ByteStreamReturner_getConnector_Params_TypeID is the unique identifier for the type ByteStreamReturner_getConnector_Params.
const ByteStreamReturner_getConnector_Params_TypeID = 0xb050e35a88385372

func NewByteStreamReturner_getConnector_Params(s *capnp.Segment) (ByteStreamReturner_getConnector_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStreamReturner_getConnector_Params(st), err
}

func NewRootByteStreamReturner_getConnector_Params(s *capnp.Segment) (ByteStreamReturner_getConnector_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStreamReturner_getConnector_Params(st), err
}

func ReadRootByteStreamReturner_getConnector_Params(msg *capnp.Message) (ByteStreamReturner_getConnector_Params, error) {
	root, err := msg.Root()
	return ByteStreamReturner_getConnector_Params(root.Struct()), err
}

func (s ByteStreamReturner_getConnector_Params) String() string {
	str, _ := text.Marshal(0xb050e35a88385372, capnp.Struct(s))
	return str
}

func (s ByteStreamReturner_getConnector_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ByteStreamReturner_getConnector_Params) DecodeFromPtr(p capnp.Ptr) ByteStreamReturner_getConnector_Params {
	return ByteStreamReturner_getConnector_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ByteStreamReturner_getConnector_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ByteStreamReturner_getConnector_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ByteStreamReturner_getConnector_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ByteStreamReturner_getConnector_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ByteStreamReturner_getConnector_Params_List is a list of ByteStreamReturner_getConnector_Params.
type ByteStreamReturner_getConnector_Params_List = capnp.StructList[ByteStreamReturner_getConnector_Params]

// NewByteStreamReturner_getConnector_Params creates a new list of ByteStreamReturner_getConnector_Params.
func NewByteStreamReturner_getConnector_Params_List(s *capnp.Segment, sz int32) (ByteStreamReturner_getConnector_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ByteStreamReturner_getConnector_Params](l), err
}

// ByteStreamReturner_getConnector_Params_Future is a wrapper for a ByteStreamReturner_getConnector_Params promised by a client call.
type ByteStreamReturner_getConnector_Params_Future struct{ *capnp.Future }

func (f ByteStreamReturner_getConnector_Params_Future) Struct() (ByteStreamReturner_getConnector_Params, error) {
	p, err := f.Future.Ptr()
	return ByteStreamReturner_getConnector_Params(p.Struct()), err
}

type ByteStreamReturner_getConnector_Results capnp.Struct

// ByteStreamReturner_getConnector_Results_TypeID is the unique identifier for the type ByteStreamReturner_getConnector_Results.
const ByteStreamReturner_getConnector_Results_TypeID = 0xab32eeaee335a878

func NewByteStreamReturner_getConnector_Results(s *capnp.Segment) (ByteStreamReturner_getConnector_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ByteStreamReturner_getConnector_Results(st), err
}

func NewRootByteStreamReturner_getConnector_Results(s *capnp.Segment) (ByteStreamReturner_getConnector_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ByteStreamReturner_getConnector_Results(st), err
}

func ReadRootByteStreamReturner_getConnector_Results(msg *capnp.Message) (ByteStreamReturner_getConnector_Results, error) {
	root, err := msg.Root()
	return ByteStreamReturner_getConnector_Results(root.Struct()), err
}

func (s ByteStreamReturner_getConnector_Results) String() string {
	str, _ := text.Marshal(0xab32eeaee335a878, capnp.Struct(s))
	return str
}

func (s ByteStreamReturner_getConnector_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ByteStreamReturner_getConnector_Results) DecodeFromPtr(p capnp.Ptr) ByteStreamReturner_getConnector_Results {
	return ByteStreamReturner_getConnector_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ByteStreamReturner_getConnector_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ByteStreamReturner_getConnector_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ByteStreamReturner_getConnector_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ByteStreamReturner_getConnector_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ByteStreamReturner_getConnector_Results) Conn() Connector {
	p, _ := capnp.Struct(s).Ptr(0)
	return Connector(p.Interface().Client())
}

func (s ByteStreamReturner_getConnector_Results) HasConn() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ByteStreamReturner_getConnector_Results) SetConn(v Connector) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// ByteStreamReturner_getConnector_Results_List is a list of ByteStreamReturner_getConnector_Results.
type ByteStreamReturner_getConnector_Results_List = capnp.StructList[ByteStreamReturner_getConnector_Results]

// NewByteStreamReturner_getConnector_Results creates a new list of ByteStreamReturner_getConnector_Results.
func NewByteStreamReturner_getConnector_Results_List(s *capnp.Segment, sz int32) (ByteStreamReturner_getConnector_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ByteStreamReturner_getConnector_Results](l), err
}

// ByteStreamReturner_getConnector_Results_Future is a wrapper for a ByteStreamReturner_getConnector_Results promised by a client call.
type ByteStreamReturner_getConnector_Results_Future struct{ *capnp.Future }

func (f ByteStreamReturner_getConnector_Results_Future) Struct() (ByteStreamReturner_getConnector_Results, error) {
	p, err := f.Future.Ptr()
	return ByteStreamReturner_getConnector_Results(p.Struct()), err
}
func (p ByteStreamReturner_getConnector_Results_Future) Conn() Connector {
	return Connector(p.Future.Field(0, nil).Client())
}

type ByteStreamReturner_inflighter_Params capnp.Struct

// ByteStreamReturner_inflighter_Params_TypeID is the unique identifier for the type ByteStreamReturner_inflighter_Params.
const ByteStreamReturner_inflighter_Params_TypeID = 0x828be092a52054ab

func NewByteStreamReturner_inflighter_Params(s *capnp.Segment) (ByteStreamReturner_inflighter_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStreamReturner_inflighter_Params(st), err
}

func NewRootByteStreamReturner_inflighter_Params(s *capnp.Segment) (ByteStreamReturner_inflighter_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStreamReturner_inflighter_Params(st), err
}

func ReadRootByteStreamReturner_inflighter_Params(msg *capnp.Message) (ByteStreamReturner_inflighter_Params, error) {
	root, err := msg.Root()
	return ByteStreamReturner_inflighter_Params(root.Struct()), err
}

func (s ByteStreamReturner_inflighter_Params) String() string {
	str, _ := text.Marshal(0x828be092a52054ab, capnp.Struct(s))
	return str
}

func (s ByteStreamReturner_inflighter_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ByteStreamReturner_inflighter_Params) DecodeFromPtr(p capnp.Ptr) ByteStreamReturner_inflighter_Params {
	return ByteStreamReturner_inflighter_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ByteStreamReturner_inflighter_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ByteStreamReturner_inflighter_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ByteStreamReturner_inflighter_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ByteStreamReturner_inflighter_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ByteStreamReturner_inflighter_Params_List is a list of ByteStreamReturner_inflighter_Params.
type ByteStreamReturner_inflighter_Params_List = capnp.StructList[ByteStreamReturner_inflighter_Params]

// NewByteStreamReturner_inflighter_Params creates a new list of ByteStreamReturner_inflighter_Params.
func NewByteStreamReturner_inflighter_Params_List(s *capnp.Segment, sz int32) (ByteStreamReturner_inflighter_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ByteStreamReturner_inflighter_Params](l), err
}

// ByteStreamReturner_inflighter_Params_Future is a wrapper for a ByteStreamReturner_inflighter_Params promised by a client call.
type ByteStreamReturner_inflighter_Params_Future struct{ *capnp.Future }

func (f ByteStreamReturner_inflighter_Params_Future) Struct() (ByteStreamReturner_inflighter_Params, error) {
	p, err := f.Future.Ptr()
	return ByteStreamReturner_inflighter_Params(p.Struct()), err
}

type ByteStreamReturner_inflighter_Results capnp.Struct

// ByteStreamReturner_inflighter_Results_TypeID is the unique identifier for the type ByteStreamReturner_inflighter_Results.
const ByteStreamReturner_inflighter_Results_TypeID = 0xbf5911c36488a144

func NewByteStreamReturner_inflighter_Results(s *capnp.Segment) (ByteStreamReturner_inflighter_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStreamReturner_inflighter_Results(st), err
}

func NewRootByteStreamReturner_inflighter_Results(s *capnp.Segment) (ByteStreamReturner_inflighter_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStreamReturner_inflighter_Results(st), err
}

func ReadRootByteStreamReturner_inflighter_Results(msg *capnp.Message) (ByteStreamReturner_inflighter_Results, error) {
	root, err := msg.Root()
	return ByteStreamReturner_inflighter_Results(root.Struct()), err
}

func (s ByteStreamReturner_inflighter_Results) String() string {
	str, _ := text.Marshal(0xbf5911c36488a144, capnp.Struct(s))
	return str
}

func (s ByteStreamReturner_inflighter_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ByteStreamReturner_inflighter_Results) DecodeFromPtr(p capnp.Ptr) ByteStreamReturner_inflighter_Results {
	return ByteStreamReturner_inflighter_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ByteStreamReturner_inflighter_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ByteStreamReturner_inflighter_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ByteStreamReturner_inflighter_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ByteStreamReturner_inflighter_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ByteStreamReturner_inflighter_Results_List is a list of ByteStreamReturner_inflighter_Results.
type ByteStreamReturner_inflighter_Results_List = capnp.StructList[ByteStreamReturner_inflighter_Results]

// NewByteStreamReturner_inflighter_Results creates a new list of ByteStreamReturner_inflighter_Results.
func NewByteStreamReturner_inflighter_Results_List(s *capnp.Segment, sz int32) (ByteStreamReturner_inflighter_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ByteStreamReturner_inflighter_Results](l), err
}

// ByteStreamReturner_inflighter_Results_Future is a wrapper for a ByteStreamReturner_inflighter_Results promised by a client call.
type ByteStreamReturner_inflighter_Results_Future struct{ *capnp.Future }

func (f ByteStreamReturner_inflighter_Results_Future) Struct() (ByteStreamReturner_inflighter_Results, error) {
	p, err := f.Future.Ptr()
	return ByteStreamReturner_inflighter_Results(p.Struct()), err
}

type Connector capnp.Client

// Connector_TypeID is the unique identifier for the type Connector.
const Connector_TypeID = 0xd86990e15ae59f2d

func (c Connector) Connect(ctx context.Context, params func(Connector_connect_Params) error) (Connector_connect_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd86990e15ae59f2d,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:Connector",
			MethodName:    "connect",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Connector_connect_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Connector_connect_Results_Future{Future: ans.Future()}, release

}

func (c Connector) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Connector) String() string {
	return "Connector(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Connector) AddRef() Connector {
	return Connector(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Connector) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Connector) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Connector) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Connector) DecodeFromPtr(p capnp.Ptr) Connector {
	return Connector(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Connector) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Connector) IsSame(other Connector) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Connector) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Connector) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Connector_Server is a Connector with a local implementation.
type Connector_Server interface {
	Connect(context.Context, Connector_connect) error
}

// Connector_NewServer creates a new Server from an implementation of Connector_Server.
func Connector_NewServer(s Connector_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Connector_Methods(nil, s), s, c)
}

// Connector_ServerToClient creates a new Client from an implementation of Connector_Server.
// The caller is responsible for calling Release on the returned Client.
func Connector_ServerToClient(s Connector_Server) Connector {
	return Connector(capnp.NewClient(Connector_NewServer(s)))
}

// Connector_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Connector_Methods(methods []server.Method, s Connector_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd86990e15ae59f2d,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:Connector",
			MethodName:    "connect",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Connect(ctx, Connector_connect{call})
		},
	})

	return methods
}

// Connector_connect holds the state for a server call to Connector.connect.
// See server.Call for documentation.
type Connector_connect struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Connector_connect) Args() Connector_connect_Params {
	return Connector_connect_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Connector_connect) AllocResults() (Connector_connect_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Connector_connect_Results(r), err
}

// Connector_List is a list of Connector.
type Connector_List = capnp.CapList[Connector]

// NewConnector_List creates a new list of Connector.
func NewConnector_List(s *capnp.Segment, sz int32) (Connector_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Connector](l), err
}

type Connector_connect_Params capnp.Struct

// Connector_connect_Params_TypeID is the unique identifier for the type Connector_connect_Params.
const Connector_connect_Params_TypeID = 0xba84dfe3c14d6fbd

func NewConnector_connect_Params(s *capnp.Segment) (Connector_connect_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Connector_connect_Params(st), err
}

func NewRootConnector_connect_Params(s *capnp.Segment) (Connector_connect_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Connector_connect_Params(st), err
}

func ReadRootConnector_connect_Params(msg *capnp.Message) (Connector_connect_Params, error) {
	root, err := msg.Root()
	return Connector_connect_Params(root.Struct()), err
}

func (s Connector_connect_Params) String() string {
	str, _ := text.Marshal(0xba84dfe3c14d6fbd, capnp.Struct(s))
	return str
}

func (s Connector_connect_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Connector_connect_Params) DecodeFromPtr(p capnp.Ptr) Connector_connect_Params {
	return Connector_connect_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Connector_connect_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Connector_connect_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Connector_connect_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Connector_connect_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Connector_connect_Params) Down() ByteStream {
	p, _ := capnp.Struct(s).Ptr(0)
	return ByteStream(p.Interface().Client())
}

func (s Connector_connect_Params) HasDown() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Connector_connect_Params) SetDown(v ByteStream) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// Connector_connect_Params_List is a list of Connector_connect_Params.
type Connector_connect_Params_List = capnp.StructList[Connector_connect_Params]

// NewConnector_connect_Params creates a new list of Connector_connect_Params.
func NewConnector_connect_Params_List(s *capnp.Segment, sz int32) (Connector_connect_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Connector_connect_Params](l), err
}

// Connector_connect_Params_Future is a wrapper for a Connector_connect_Params promised by a client call.
type Connector_connect_Params_Future struct{ *capnp.Future }

func (f Connector_connect_Params_Future) Struct() (Connector_connect_Params, error) {
	p, err := f.Future.Ptr()
	return Connector_connect_Params(p.Struct()), err
}
func (p Connector_connect_Params_Future) Down() ByteStream {
	return ByteStream(p.Future.Field(0, nil).Client())
}

type Connector_connect_Results capnp.Struct

// Connector_connect_Results_TypeID is the unique identifier for the type Connector_connect_Results.
const Connector_connect_Results_TypeID = 0xdd03c32a9c279310

func NewConnector_connect_Results(s *capnp.Segment) (Connector_connect_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Connector_connect_Results(st), err
}

func NewRootConnector_connect_Results(s *capnp.Segment) (Connector_connect_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Connector_connect_Results(st), err
}

func ReadRootConnector_connect_Results(msg *capnp.Message) (Connector_connect_Results, error) {
	root, err := msg.Root()
	return Connector_connect_Results(root.Struct()), err
}

func (s Connector_connect_Results) String() string {
	str, _ := text.Marshal(0xdd03c32a9c279310, capnp.Struct(s))
	return str
}

func (s Connector_connect_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Connector_connect_Results) DecodeFromPtr(p capnp.Ptr) Connector_connect_Results {
	return Connector_connect_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Connector_connect_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Connector_connect_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Connector_connect_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Connector_connect_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Connector_connect_Results) Up() ByteStream {
	p, _ := capnp.Struct(s).Ptr(0)
	return ByteStream(p.Interface().Client())
}

func (s Connector_connect_Results) HasUp() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Connector_connect_Results) SetUp(v ByteStream) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// Connector_connect_Results_List is a list of Connector_connect_Results.
type Connector_connect_Results_List = capnp.StructList[Connector_connect_Results]

// NewConnector_connect_Results creates a new list of Connector_connect_Results.
func NewConnector_connect_Results_List(s *capnp.Segment, sz int32) (Connector_connect_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Connector_connect_Results](l), err
}

// Connector_connect_Results_Future is a wrapper for a Connector_connect_Results promised by a client call.
type Connector_connect_Results_Future struct{ *capnp.Future }

func (f Connector_connect_Results_Future) Struct() (Connector_connect_Results, error) {
	p, err := f.Future.Ptr()
	return Connector_connect_Results(p.Struct()), err
}
func (p Connector_connect_Results_Future) Up() ByteStream {
	return ByteStream(p.Future.Field(0, nil).Client())
}

type ByteStream capnp.Client

// ByteStream_TypeID is the unique identifier for the type ByteStream.
const ByteStream_TypeID = 0xb45bc9c79a817b99

func (c ByteStream) Write(ctx context.Context, params func(ByteStream_write_Params) error) (ByteStream_write_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xb45bc9c79a817b99,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:ByteStream",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ByteStream_write_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ByteStream_write_Results_Future{Future: ans.Future()}, release

}

func (c ByteStream) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c ByteStream) String() string {
	return "ByteStream(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c ByteStream) AddRef() ByteStream {
	return ByteStream(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c ByteStream) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c ByteStream) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c ByteStream) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (ByteStream) DecodeFromPtr(p capnp.Ptr) ByteStream {
	return ByteStream(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c ByteStream) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c ByteStream) IsSame(other ByteStream) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c ByteStream) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c ByteStream) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A ByteStream_Server is a ByteStream with a local implementation.
type ByteStream_Server interface {
	Write(context.Context, ByteStream_write) error
}

// ByteStream_NewServer creates a new Server from an implementation of ByteStream_Server.
func ByteStream_NewServer(s ByteStream_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ByteStream_Methods(nil, s), s, c)
}

// ByteStream_ServerToClient creates a new Client from an implementation of ByteStream_Server.
// The caller is responsible for calling Release on the returned Client.
func ByteStream_ServerToClient(s ByteStream_Server) ByteStream {
	return ByteStream(capnp.NewClient(ByteStream_NewServer(s)))
}

// ByteStream_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ByteStream_Methods(methods []server.Method, s ByteStream_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb45bc9c79a817b99,
			MethodID:      0,
			InterfaceName: "byte-stream.capnp:ByteStream",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, ByteStream_write{call})
		},
	})

	return methods
}

// ByteStream_write holds the state for a server call to ByteStream.write.
// See server.Call for documentation.
type ByteStream_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ByteStream_write) Args() ByteStream_write_Params {
	return ByteStream_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ByteStream_write) AllocResults() (ByteStream_write_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStream_write_Results(r), err
}

// ByteStream_List is a list of ByteStream.
type ByteStream_List = capnp.CapList[ByteStream]

// NewByteStream_List creates a new list of ByteStream.
func NewByteStream_List(s *capnp.Segment, sz int32) (ByteStream_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[ByteStream](l), err
}

type ByteStream_write_Params capnp.Struct

// ByteStream_write_Params_TypeID is the unique identifier for the type ByteStream_write_Params.
const ByteStream_write_Params_TypeID = 0xf38674615ae8d859

func NewByteStream_write_Params(s *capnp.Segment) (ByteStream_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ByteStream_write_Params(st), err
}

func NewRootByteStream_write_Params(s *capnp.Segment) (ByteStream_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ByteStream_write_Params(st), err
}

func ReadRootByteStream_write_Params(msg *capnp.Message) (ByteStream_write_Params, error) {
	root, err := msg.Root()
	return ByteStream_write_Params(root.Struct()), err
}

func (s ByteStream_write_Params) String() string {
	str, _ := text.Marshal(0xf38674615ae8d859, capnp.Struct(s))
	return str
}

func (s ByteStream_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ByteStream_write_Params) DecodeFromPtr(p capnp.Ptr) ByteStream_write_Params {
	return ByteStream_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ByteStream_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ByteStream_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ByteStream_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ByteStream_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ByteStream_write_Params) Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s ByteStream_write_Params) HasBytes() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ByteStream_write_Params) SetBytes(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// ByteStream_write_Params_List is a list of ByteStream_write_Params.
type ByteStream_write_Params_List = capnp.StructList[ByteStream_write_Params]

// NewByteStream_write_Params creates a new list of ByteStream_write_Params.
func NewByteStream_write_Params_List(s *capnp.Segment, sz int32) (ByteStream_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ByteStream_write_Params](l), err
}

// ByteStream_write_Params_Future is a wrapper for a ByteStream_write_Params promised by a client call.
type ByteStream_write_Params_Future struct{ *capnp.Future }

func (f ByteStream_write_Params_Future) Struct() (ByteStream_write_Params, error) {
	p, err := f.Future.Ptr()
	return ByteStream_write_Params(p.Struct()), err
}

type ByteStream_write_Results capnp.Struct

// ByteStream_write_Results_TypeID is the unique identifier for the type ByteStream_write_Results.
const ByteStream_write_Results_TypeID = 0xbb0363e0ee429226

func NewByteStream_write_Results(s *capnp.Segment) (ByteStream_write_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStream_write_Results(st), err
}

func NewRootByteStream_write_Results(s *capnp.Segment) (ByteStream_write_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ByteStream_write_Results(st), err
}

func ReadRootByteStream_write_Results(msg *capnp.Message) (ByteStream_write_Results, error) {
	root, err := msg.Root()
	return ByteStream_write_Results(root.Struct()), err
}

func (s ByteStream_write_Results) String() string {
	str, _ := text.Marshal(0xbb0363e0ee429226, capnp.Struct(s))
	return str
}

func (s ByteStream_write_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ByteStream_write_Results) DecodeFromPtr(p capnp.Ptr) ByteStream_write_Results {
	return ByteStream_write_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ByteStream_write_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ByteStream_write_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ByteStream_write_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ByteStream_write_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ByteStream_write_Results_List is a list of ByteStream_write_Results.
type ByteStream_write_Results_List = capnp.StructList[ByteStream_write_Results]

// NewByteStream_write_Results creates a new list of ByteStream_write_Results.
func NewByteStream_write_Results_List(s *capnp.Segment, sz int32) (ByteStream_write_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ByteStream_write_Results](l), err
}

// ByteStream_write_Results_Future is a wrapper for a ByteStream_write_Results promised by a client call.
type ByteStream_write_Results_Future struct{ *capnp.Future }

func (f ByteStream_write_Results_Future) Struct() (ByteStream_write_Results, error) {
	p, err := f.Future.Ptr()
	return ByteStream_write_Results(p.Struct()), err
}

const schema_8f5d14e1c273738e = "x\xda\x9cT_H\x14k\x14?g\xbeYG.\xec" +
	"\xdd\xfb\xdd\xf1\xbe\xc8\xf5\xea\x15\xef\xbd\xdc\x05\x97\\\x8b" +
	"\"\x08\xc5\x0a{\x09vW{p\xa3\x87u\xfd\xb2\x0d" +
	"wGgf3\x11\x89\"J(\xac\x0c\x1f\x92\"|" +
	"\x08\x0c1|\xd0 #\"E\"\xa1\x87|\xf2E\xd2" +
	",\xa8\x1e\x04\xe9-\x92\x89\xef\x9bffw\xfdC\xf8" +
	"60\xe7\xfc~\xbf\xf3\xfb\x9d\xf3\xed\x19\xc7z\xb9\xc6" +
	"\xbf\xbf\x08\xa4\xe81_\x915\xd6\\\xf1`p\xf9\xda" +
	"%\xa0\xff \x80\xac\x00\xd4\"\x99F\x90\xad\xf9\xe1\xbf" +
	"\xb5\xbdS\x13\xfd@\x7f'\xd6\x80a\xcc\xac\x94\x9c\xba" +
	"\x01\x80\xb5\xebR\x10U$\x0a\x80\xba!]UO\xf0" +
	"/\xeb\xfc\xe8\xbe\xd5Gk\xe11\x1b\xc7\x87\x1c\xe8\x10" +
	"Y@@5J\xea\x00-\xbd\xe9@\x7f|52\x91" +
	"C\xd4E\xe69\xd1\x9d\xde\x8b\xc3/_\x9d\x9c,$" +
	"R\x19\xf9\xacv\x09\x9e4iT\x87\x04O\xef\xc0\xaf" +
	"\xcd\xba\xf5~\x12h\xa9\x03\xd3G\x82\x1c\xe6\x99v\xfc" +
	"\xc5\xea\xdb\xcb\xd3@\xfft\x150\x12\xe7\x0a\xba\x84\x82" +
	"\x7f\x07\x1b\xd6\x96\x93\xe4)\xd02\xa7\xf5\x16\xff/[" +
	"GF\xfa\xdbfi\xcb\xf3\x1cm}d\x86\xff\x19:" +
	"\xaa]\xaf\xf8\xfa\xd7\xbcMg\x83\xa6I\x98\x83f\x05" +
	"\xe8\xb7\xc7\xfa\xa8\xf1\xe9\xe1\xebM\xe2\x87\xc8\x82:\"" +
	"\xc4\xdf#\x8d\xea\x9c\x10_}\xffC|\xe5fjq" +
	"S\xf18y\xa7>\x11\xc5S\xa4Q]\x12\xc5\xbf\xdd" +
	"\xfe\xefnp\x96,\xe5\xce3GZ9\xf5\x1bA\xdd" +
	"\xb2\xf81\x9e0\xaf|\xb1\xe7\xb1\x0b\xd6I\x8c\x17l" +
	"\x90:\xa8\xb6Z{LVm\x98\xba\x8f%\xd2\xa1d" +
	"\xa23\xd3y\xb0\xa1\xc7dM\xa6\xce\x12\xe9\x183\xb3" +
	"z\x86\xe9\xa1T\xe6tG\xaa\xfd\x8c\xc9\xf4\xaa\xbaH" +
	"BO\xa4\x0d\xb7\x91l\xd7\x18\xe0\x9d\x11\xc4h1\xf1" +
	"\x01\xb8\xd9\xa2\xb3\x05\xb4\xe6,H\xf4\x7f\x05\xd1]0" +
	"tL\xa6eq\x90\xe8\x1f\x8a\xd5\xce\xcc\xc3Z&\xc3" +
	" \x9045\xbd\x1e-G\x09\x10\xa6\xd7c\x04\xd1\x15" +
	"R\xb4\xe3\x04\x0e\x10\x87\xa9\x8a1#\xdba\xa2\x11\x95" +
	"\x89\x0c #\x00\xf5\x07\x01\xa2\xc5\x04\xa3%\x12\x06\x92" +
	"Z&\x83\xd4\x8b\x02\x10)\xec\x8a\xc96\x0b\xc0\xed\x95" +
	"\x0a{\x03\xbc\x99\xdb$\x0b\x9b\x9c\xc0\xd0\xd9DJ\xc3" +
	" Q\x9fR\xde\xad\xa7L\x96?r\x8e\xf7ML?" +
	"\x97J2\xce^\x15I\x04\xf2\"\x92\xbd2WY(" +
	"i\x7f\x09\x85$\xbd\xad\x15mZ7\xb7\xc2\xbd\xbf\x02" +
	"+\xe4\xad\xac\x08\x09\xa9\xb6\xcb\xc4\xf4t\xfc\xf2\xb3;" +
	"f\xe7c\x80\xd3\xb8\xf5\x981V.\xcar\xa5Wz" +
	"\xd2\x95VCG\xea=Q\x05\xca\xa5BPd^\x0a" +
	"\xce\x0b\x82\xcemSZ)RP\xda\x99\x99\x9f\x81T" +
	"h\xaebj\xba\x87\xe4\xbc8\xe8\x9c*\xa5\x0d\x02\xe9" +
	"\xc2\x8f\x00\xf2\xd1v\x8c\x8a\xdb\xa2\x14\x0c\\\xea\x0dL" +
	"\xb2\x9d\xbbLJli\xfe9\x84=\xdcr\x0ea\xa0" +
	"\x1f$\xf4\x03~\x0f\x00\x00\xff\xff0\x9f\xe3\xbf"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_8f5d14e1c273738e,
		Nodes: []uint64{
			0x828be092a52054ab,
			0x88b0b5346f219aca,
			0xab32eeaee335a878,
			0xb050e35a88385372,
			0xb45bc9c79a817b99,
			0xb4e4ff72540e8e7b,
			0xba84dfe3c14d6fbd,
			0xbb0363e0ee429226,
			0xbf5911c36488a144,
			0xca1efa208c6f4595,
			0xcda9e973a872b6fc,
			0xd86990e15ae59f2d,
			0xdd03c32a9c279310,
			0xf38674615ae8d859,
		},
		Compressed: true,
	})
}
